### ISSUE TITLE
Flutter 2 and maybe null safety

### ISSUE THREAD

**Issue by neiljaywarner** [Bwolfs2/dirt_arch#1]
Seems awesome!
Can you get it to work on flutter 2 ? or at least tell us what version we should use..
i got Launching lib/main.dart on sdk gphone x86 in debug mode...
Running Gradle task 'assembleDebug'...
../../../flutter/.pub-cache/hosted/pub.dartlang.org/date_range_picker-1.0.6/lib/date_range_picker.dart:1152:44: Error: Method not found: 'ButtonTheme.bar'.
    final Widget actions = new ButtonTheme.bar(
                                           ^^^
../../../flutter/.pub-cache/hosted/pub.dartlang.org/country_pickers-1.3.0/lib/utils/my_alert_dialog.dart:139:36: Error: Method not found: 'ButtonTheme.bar'.
      children.add(new ButtonTheme.bar(
                                   ^^^

FAILURE: Build failed with an exception.

* Where:
Script '/Users/neilw/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 991

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/neilw/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 2s
Exception: Gradle task assembleDebug failed with exit code 1

thanks!

**Comment by Bwolfs2** [comment]
Fixed =)
